### ISSUE TITLE
Outils d'annotation mémoire restante faible

### ISSUE THREAD

**Issue by JulienGarcia54** [NEXT-BIM/next-bim-releases#1]
Bonjour,
je n'arrive pas à enregistrer les BCF sur mon ordinateur.

Quand je fais "exporter" après avoir cliqué sur les annotations, j'ai une fenêtre d'attente qui reste bloquée à "veuillez patienter".

Et j'ai aussi un message d'erreur "outils d'annotation mémoire restante faible" qui me dit que la mémoire interne est limitée, mais en connectant le casque à mon ordi, je n'arrive pas à retirer des dossiers pour libérer de l'espace.

![ad437746-60bc-474a-9397-66785b81fa0e](https://user-images.githubusercontent.com/49711865/207885502-80e5351a-5c33-4699-ba41-0134d7dcfba3.jpg)

Je ne peux accéder au portail Windows avec l'IP du casque depuis un navigateur chrome, car un nom d'utilisateur et mot de passe autre que ceux de l'ouverture de ma session Windows sont demandé.

Cordialement.

**Comment by CorentinCdx** [comment]
Bonjour Julien, 

Merci pour votre retour.
La solution provisoire est d'exporter les annotations au format .BCF depuis la vue en mode "Tabletop".
Le problème depuis la vue immersive est en cours de résolution, merci pour votre compréhension.

Concernant la mémoire, il faut vérifier l'espace restant disponible en branchant votre HoloLens à votre PC en USB. Pour rappel, l'HoloLens dispose de 64gb de mémoire. Il est possible que le message d'erreur soit un bogue provenant de l'appareil. Si l'espace est disponible sur votre HoloLens et que le problème réitere, il faudrait le signaler au support de votre fournisseur HoloLens ou directement au support Microsoft via le lien suivant : [http://support.microsoft.com/oas/default.aspx?prid=15875]

Pour accéder au Windows Device Portal (WDP), il faut utiliser le nom d'utilisateur et le mot de passe définis lors de la mise en route de l'Hololens et non pas les identifiants de la session liée à l'e-mail. 

Cordialement,

Corentin

**Comment by CorentinCdx** [comment]
Nous avons réalisé une optimisation des images integrées dans les .BCF.
Le nombre d'annotations actives dans NEXT-BIM Explorer (1 photo / bcf) est d'environ 600.
